// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwbr7kITBlkg88PiL6qwgYKEVJrEzXwKc',
    appId: '1:101099602427:web:4fcf9103102eb994cacb5e',
    messagingSenderId: '101099602427',
    projectId: 'raychat-bbab7',
    authDomain: 'raychat-bbab7.firebaseapp.com',
    storageBucket: 'raychat-bbab7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbRDtwAf80CoIA28nR7CPsnxzhG3_dWg4',
    appId: '1:101099602427:android:fe201a217abfbad8cacb5e',
    messagingSenderId: '101099602427',
    projectId: 'raychat-bbab7',
    storageBucket: 'raychat-bbab7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAja5gSYQCy-Y1qUm4jgA0W7P8svZyc9Ks',
    appId: '1:101099602427:ios:fe0ad0151aab7ef1cacb5e',
    messagingSenderId: '101099602427',
    projectId: 'raychat-bbab7',
    storageBucket: 'raychat-bbab7.appspot.com',
    iosClientId: '101099602427-e4o6jffes62568jdoahghkjb606uga25.apps.googleusercontent.com',
    iosBundleId: 'com.raywenderlich.RayChat',
  );
}
